# Generated by Django 3.2.4 on 2021-07-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
    ]
